import type { Metadata } from "next";
import { League_Script, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// Load Poppins font with desired weights
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: 'swap',
});


export const leagueScript = League_Script({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',

});




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <div className="min-h-[calc(100vh-185px)]">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
